#!/usr/bin/env python3
"""
Build derived occlusion assets from an existing STEP asset manifest.

The script creates variants such as:
  - points/<sample_id>__occ_000.npz
  - images/<sample_id>__occ_000/view_000.png
  - masks/<sample_id>__occ_000/view_000_mask.png
  - steps/<sample_id>__occ_000.step, optionally
  - labels/<sample_id>__occ_000.json

Occlusion parameters are stored in unit-cube coordinates [0, 1]^3. Existing
point clouds generated by build_step_assets.py are expected to be in centered
unit-cube coordinates [-0.5, 0.5]^3, so the conversion is explicit.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import signal
import sys
from dataclasses import dataclass
from itertools import repeat
from multiprocessing import Pool
from pathlib import Path
from typing import Any, Iterable, Optional, Sequence

import numpy as np
import trimesh
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFilter
from tqdm import tqdm

SRC_ROOT = Path(__file__).resolve().parents[1]
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from cad_data_gen.build_step_assets import (  # noqa: E402
    _view_basis,
    get_view_fronts,
    load_step_as_mesh,
    normalize_trimesh_unit_cube,
    render_step_views_with_blender,
    render_views_to_png,
    resolve_blender_bin,
)

try:
    import cadquery as cq
except ModuleNotFoundError:
    cq = None


VALID_DIMS = {"point_cloud", "image", "step"}
VALID_MODES = {"cutout", "occluder", "mixed"}


@dataclass(frozen=True)
class OcclusionSpec:
    source_sample_id: str
    variant_id: str
    variant_sample_id: str
    mode: str
    target_dims: tuple[str, ...]
    primitive: str
    center_unit: tuple[float, float, float]
    size_unit: tuple[float, float, float]
    seed: int
    views: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "source_sample_id": self.source_sample_id,
            "variant_id": self.variant_id,
            "variant_sample_id": self.variant_sample_id,
            "mode": self.mode,
            "target_dims": list(self.target_dims),
            "primitive": self.primitive,
            "center_unit": list(self.center_unit),
            "size_unit": list(self.size_unit),
            "seed": self.seed,
            "views": self.views,
        }


@dataclass(frozen=True)
class ProcessArgs:
    source_assets_dir: Path
    step_root: Path
    output_dir: Path
    target_dims: tuple[str, ...]
    mode: str
    num_views: int
    img_size: int
    camera_distance: float
    render_width: int
    render_height: int
    render_backend: str
    blender_bin: str
    blender_script: Optional[Path]
    blender_engine: str
    blender_samples: int
    blender_style: str
    foreground_occluder_size_min: float
    foreground_occluder_size_max: float
    foreground_occluder_depth: float
    triangle_face_tol: float
    angle_tol_rads: float
    variants_per_sample: int
    seed: int
    size_min: float
    size_max: float
    min_removed_ratio: float
    max_removed_ratio: float
    max_spec_attempts: int
    num_points: Optional[int]
    fixed_num_points: bool
    occluder_color: tuple[int, int, int]
    highlight_cutout: bool
    highlight_color: tuple[int, int, int]
    highlight_alpha: float
    outline_color: tuple[int, int, int]
    outline_width: int
    skip_existing: bool


def _as_float_list(values: Sequence[float]) -> list[float]:
    return [float(v) for v in values]


def _json_dump(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=True, indent=2, sort_keys=True)
        f.write("\n")


def _stable_seed(base_seed: int, sample_id: str, variant_index: int) -> int:
    raw = f"{base_seed}:{sample_id}:{variant_index}".encode("utf-8")
    digest = hashlib.sha256(raw).digest()
    return int.from_bytes(digest[:8], "little") % (2**32 - 1)


def _parse_dims(raw: str) -> tuple[str, ...]:
    dims = tuple(part.strip() for part in raw.split(",") if part.strip())
    unknown = sorted(set(dims) - VALID_DIMS)
    if unknown:
        raise ValueError(f"unknown target dims: {unknown}")
    if not dims:
        raise ValueError("at least one target dim is required")
    return dims


def _parse_color(raw: str) -> tuple[int, int, int]:
    parts = [int(p.strip()) for p in raw.split(",")]
    if len(parts) != 3 or any(p < 0 or p > 255 for p in parts):
        raise ValueError("--occluder-color must be R,G,B with values in [0,255]")
    return tuple(parts)


def _load_manifest(path: Path, limit: Optional[int]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            records.append(json.loads(line))
            if limit is not None and len(records) >= limit:
                break
    return records


def _unit_points(points_centered: np.ndarray) -> np.ndarray:
    return np.clip(np.asarray(points_centered, dtype=np.float64) + 0.5, 0.0, 1.0)


def _box_bounds(
    center_unit: Sequence[float],
    size_unit: Sequence[float],
) -> tuple[np.ndarray, np.ndarray]:
    center = np.asarray(center_unit, dtype=np.float64)
    size = np.asarray(size_unit, dtype=np.float64)
    return center - size * 0.5, center + size * 0.5


def _points_in_unit_box(
    points_centered: np.ndarray,
    center_unit: Sequence[float],
    size_unit: Sequence[float],
) -> np.ndarray:
    points = _unit_points(points_centered)
    low, high = _box_bounds(center_unit, size_unit)
    return np.all((points >= low) & (points <= high), axis=1)


def _mesh_face_mask_in_box(
    mesh_centered: trimesh.Trimesh,
    center_unit: Sequence[float],
    size_unit: Sequence[float],
) -> np.ndarray:
    centers_unit = np.asarray(mesh_centered.triangles_center, dtype=np.float64) + 0.5
    low, high = _box_bounds(center_unit, size_unit)
    return np.all((centers_unit >= low) & (centers_unit <= high), axis=1)


def _cutout_mesh_by_box(
    mesh_centered: trimesh.Trimesh,
    spec: OcclusionSpec,
) -> tuple[trimesh.Trimesh, dict[str, float]]:
    removed_faces = _mesh_face_mask_in_box(
        mesh_centered,
        spec.center_unit,
        spec.size_unit,
    )
    keep_faces = ~removed_faces
    removed_ratio = float(removed_faces.mean()) if len(removed_faces) else 0.0
    if not keep_faces.any():
        raise ValueError("mesh cutout removed all faces")

    mesh = mesh_centered.copy()
    mesh.update_faces(keep_faces)
    mesh.remove_unreferenced_vertices()
    if len(mesh.faces) == 0 or len(mesh.vertices) == 0:
        raise ValueError("mesh cutout produced an empty mesh")
    return mesh, {"mesh_face_removed_ratio": removed_ratio}


def _convex_hull(points: np.ndarray) -> list[tuple[float, float]]:
    pts = sorted({(float(x), float(y)) for x, y in points})
    if len(pts) <= 1:
        return pts

    def cross(
        origin: tuple[float, float],
        a: tuple[float, float],
        b: tuple[float, float],
    ) -> float:
        return (a[0] - origin[0]) * (b[1] - origin[1]) - (
            a[1] - origin[1]
        ) * (b[0] - origin[0])

    lower: list[tuple[float, float]] = []
    for point in pts:
        while len(lower) >= 2 and cross(lower[-2], lower[-1], point) <= 0:
            lower.pop()
        lower.append(point)

    upper: list[tuple[float, float]] = []
    for point in reversed(pts):
        while len(upper) >= 2 and cross(upper[-2], upper[-1], point) <= 0:
            upper.pop()
        upper.append(point)

    return lower[:-1] + upper[:-1]


def _box_corners(center_unit: Sequence[float], size_unit: Sequence[float]) -> np.ndarray:
    low, high = _box_bounds(center_unit, size_unit)
    return np.asarray(
        [
            [x, y, z]
            for x in (low[0], high[0])
            for y in (low[1], high[1])
            for z in (low[2], high[2])
        ],
        dtype=np.float64,
    )


def _project_unit_points(
    points_unit: np.ndarray,
    mesh_vertices_unit: np.ndarray,
    front: Sequence[float],
    img_size: int,
) -> np.ndarray:
    right, true_up, _ = _view_basis(front)
    centered_mesh = np.asarray(mesh_vertices_unit, dtype=np.float64) - np.array(
        [0.5, 0.5, 0.5]
    )
    mesh_xy = np.stack([centered_mesh @ right, centered_mesh @ true_up], axis=1)
    span = float(np.max(np.ptp(mesh_xy, axis=0)))
    if span < 1e-8:
        raise ValueError("projected mesh is degenerate")

    centered_points = np.asarray(points_unit, dtype=np.float64) - np.array(
        [0.5, 0.5, 0.5]
    )
    xy = np.stack([centered_points @ right, centered_points @ true_up], axis=1)
    pad = img_size * 0.12
    scale = (img_size - 2 * pad) / span
    pixels = np.empty_like(xy)
    pixels[:, 0] = xy[:, 0] * scale + img_size / 2.0
    pixels[:, 1] = img_size / 2.0 - xy[:, 1] * scale
    return pixels


def _project_unit_points_with_depth(
    points_unit: np.ndarray,
    mesh_vertices_unit: np.ndarray,
    front: Sequence[float],
    img_size: int,
) -> tuple[np.ndarray, np.ndarray]:
    right, true_up, direction = _view_basis(front)
    centered_mesh = np.asarray(mesh_vertices_unit, dtype=np.float64) - np.array(
        [0.5, 0.5, 0.5]
    )
    mesh_xy = np.stack([centered_mesh @ right, centered_mesh @ true_up], axis=1)
    span = float(np.max(np.ptp(mesh_xy, axis=0)))
    if span < 1e-8:
        raise ValueError("projected mesh is degenerate")

    centered_points = np.asarray(points_unit, dtype=np.float64) - np.array(
        [0.5, 0.5, 0.5]
    )
    xy = np.stack([centered_points @ right, centered_points @ true_up], axis=1)
    z = centered_points @ direction
    pad = img_size * 0.12
    scale = (img_size - 2 * pad) / span
    pixels = np.empty_like(xy)
    pixels[:, 0] = xy[:, 0] * scale + img_size / 2.0
    pixels[:, 1] = img_size / 2.0 - xy[:, 1] * scale
    return pixels, z


def _rasterize_depth(
    pixels: np.ndarray,
    depths: np.ndarray,
    faces: np.ndarray,
    img_size: int,
) -> tuple[np.ndarray, np.ndarray]:
    z_buffer = np.full((img_size, img_size), -np.inf, dtype=np.float64)
    mask = np.zeros((img_size, img_size), dtype=bool)
    for tri in np.asarray(faces, dtype=np.int32):
        pts = pixels[tri]
        min_xy = np.floor(pts.min(axis=0)).astype(int)
        max_xy = np.ceil(pts.max(axis=0)).astype(int)
        min_x = max(0, min_xy[0])
        min_y = max(0, min_xy[1])
        max_x = min(img_size - 1, max_xy[0])
        max_y = min(img_size - 1, max_xy[1])
        if min_x > max_x or min_y > max_y:
            continue

        p0, p1, p2 = pts
        denom = (p1[1] - p2[1]) * (p0[0] - p2[0]) + (p2[0] - p1[0]) * (
            p0[1] - p2[1]
        )
        if abs(float(denom)) < 1e-12:
            continue

        yy, xx = np.mgrid[min_y : max_y + 1, min_x : max_x + 1]
        px = xx + 0.5
        py = yy + 0.5
        w0 = ((p1[1] - p2[1]) * (px - p2[0]) + (p2[0] - p1[0]) * (py - p2[1])) / denom
        w1 = ((p2[1] - p0[1]) * (px - p2[0]) + (p0[0] - p2[0]) * (py - p2[1])) / denom
        w2 = 1.0 - w0 - w1
        inside = (w0 >= -1e-6) & (w1 >= -1e-6) & (w2 >= -1e-6)
        if not inside.any():
            continue

        z_tri = depths[tri]
        z_pixels = w0 * z_tri[0] + w1 * z_tri[1] + w2 * z_tri[2]
        current = z_buffer[min_y : max_y + 1, min_x : max_x + 1]
        update = inside & (z_pixels > current)
        if not update.any():
            continue
        current[update] = z_pixels[update]
        mask[min_y : max_y + 1, min_x : max_x + 1][update] = True
    return z_buffer, mask


def _box_mesh_unit(
    center_unit: Sequence[float],
    size_unit: Sequence[float],
) -> tuple[np.ndarray, np.ndarray]:
    low, high = _box_bounds(center_unit, size_unit)
    x0, y0, z0 = low
    x1, y1, z1 = high
    vertices = np.asarray(
        [
            [x0, y0, z0],
            [x1, y0, z0],
            [x1, y1, z0],
            [x0, y1, z0],
            [x0, y0, z1],
            [x1, y0, z1],
            [x1, y1, z1],
            [x0, y1, z1],
        ],
        dtype=np.float64,
    )
    faces = np.asarray(
        [
            [0, 1, 2],
            [0, 2, 3],
            [4, 6, 5],
            [4, 7, 6],
            [0, 4, 5],
            [0, 5, 1],
            [1, 5, 6],
            [1, 6, 2],
            [2, 6, 7],
            [2, 7, 3],
            [3, 7, 4],
            [3, 4, 0],
        ],
        dtype=np.int32,
    )
    return vertices, faces


def _box_mask_for_view(
    mesh_centered: trimesh.Trimesh,
    spec: OcclusionSpec,
    front: Sequence[float],
    img_size: int,
) -> Image.Image:
    vertices_unit = np.asarray(mesh_centered.vertices, dtype=np.float64) + 0.5
    box_pixels = _project_unit_points(
        _box_corners(spec.center_unit, spec.size_unit),
        vertices_unit,
        front,
        img_size,
    )
    hull = _convex_hull(box_pixels)
    mask = Image.new("L", (img_size, img_size), 0)
    if len(hull) >= 3:
        draw = ImageDraw.Draw(mask)
        draw.polygon(hull, fill=255)
    return mask


def _visible_box_mask_for_view(
    mesh_centered: trimesh.Trimesh,
    spec: OcclusionSpec,
    front: Sequence[float],
    img_size: int,
    depth_epsilon: float = 0.01,
) -> Image.Image:
    model_vertices = np.asarray(mesh_centered.vertices, dtype=np.float64) + 0.5
    model_faces = np.asarray(mesh_centered.faces, dtype=np.int32)
    model_pixels, model_depths = _project_unit_points_with_depth(
        model_vertices,
        model_vertices,
        front,
        img_size,
    )
    model_z, model_mask = _rasterize_depth(
        model_pixels,
        model_depths,
        model_faces,
        img_size,
    )

    box_vertices, box_faces = _box_mesh_unit(spec.center_unit, spec.size_unit)
    box_pixels, box_depths = _project_unit_points_with_depth(
        box_vertices,
        model_vertices,
        front,
        img_size,
    )
    box_z, box_mask = _rasterize_depth(
        box_pixels,
        box_depths,
        box_faces,
        img_size,
    )
    visible = box_mask & model_mask & (box_z >= model_z - depth_epsilon)
    return Image.fromarray((visible.astype(np.uint8) * 255), mode="L")


def _uses_foreground_occluder(args: ProcessArgs, spec: OcclusionSpec) -> bool:
    return args.render_backend == "blender-step" and spec.mode == "occluder"


def _foreground_shape_points(
    shape: str,
    center: np.ndarray,
    right: np.ndarray,
    up: np.ndarray,
    half_w: float,
    half_h: float,
) -> list[tuple[float, float]]:
    if shape == "triangle":
        local = [(0.0, 0.58), (-0.5, -0.29), (0.5, -0.29)]
    elif shape == "ellipse":
        local = [
            (0.5 * np.cos(2.0 * np.pi * i / 32.0), 0.5 * np.sin(2.0 * np.pi * i / 32.0))
            for i in range(32)
        ]
    elif shape == "hexagon":
        local = [
            (0.5 * np.cos(2.0 * np.pi * i / 6.0), 0.5 * np.sin(2.0 * np.pi * i / 6.0))
            for i in range(6)
        ]
    else:
        local = [(-0.5, -0.5), (0.5, -0.5), (0.5, 0.5), (-0.5, 0.5)]
    points = [
        center + right * (x * half_w * 2.0) + up * (y * half_h * 2.0)
        for x, y in local
    ]
    return [(float(x), float(y)) for x, y in points]


def _foreground_mask_for_view(view_config: dict[str, Any], img_size: int) -> Image.Image:
    offset_x, offset_y = [float(v) for v in view_config.get("offset_xy", [0.0, 0.0])]
    size_x, size_y = [float(v) for v in view_config.get("size_xy", [0.28, 0.28])]
    angle = np.deg2rad(float(view_config.get("angle_degrees", 0.0)))
    shape = str(view_config.get("shape", "rectangle"))

    center = np.asarray(
        [
            (0.5 + offset_x) * img_size,
            (0.5 - offset_y) * img_size,
        ],
        dtype=np.float64,
    )
    half_w = size_x * img_size * 0.5
    half_h = size_y * img_size * 0.5
    right = np.asarray([np.cos(angle), -np.sin(angle)], dtype=np.float64)
    up = np.asarray([np.sin(angle), np.cos(angle)], dtype=np.float64)
    points = _foreground_shape_points(shape, center, right, up, half_w, half_h)
    mask = Image.new("L", (img_size, img_size), 0)
    draw = ImageDraw.Draw(mask)
    draw.polygon(points, fill=255)
    return mask


def _make_model_anchored_foreground_occluder_config(
    mesh_centered: trimesh.Trimesh,
    fronts: Sequence[Sequence[float]],
    img_size: int,
    seed: int,
    color: Sequence[int | float],
    size_min: float,
    size_max: float,
    depth: float,
) -> dict[str, Any]:
    rng = np.random.default_rng(seed)
    shapes = ("rectangle", "ellipse", "triangle", "hexagon")
    model_vertices = np.asarray(mesh_centered.vertices, dtype=np.float64) + 0.5
    anchors = np.asarray(mesh_centered.triangles_center, dtype=np.float64) + 0.5
    if len(anchors) == 0:
        anchors = model_vertices

    views: list[dict[str, Any]] = []
    for front in fronts:
        width = float(rng.uniform(size_min, size_max))
        height = float(rng.uniform(size_min, size_max))
        shape = str(rng.choice(shapes))
        projected = _project_unit_points(anchors, model_vertices, front, img_size=img_size)
        x_norm = projected[:, 0] / float(img_size)
        y_norm = projected[:, 1] / float(img_size)
        margin_x = width * 0.5
        margin_y = height * 0.5
        valid = (
            (x_norm >= margin_x)
            & (x_norm <= 1.0 - margin_x)
            & (y_norm >= margin_y)
            & (y_norm <= 1.0 - margin_y)
        )
        candidates = projected[valid] if valid.any() else projected
        anchor = candidates[int(rng.integers(0, len(candidates)))]
        offset_x = float(anchor[0] / float(img_size) - 0.5)
        offset_y = float(0.5 - anchor[1] / float(img_size))
        jitter_x = float(rng.uniform(-0.12, 0.12) * width)
        jitter_y = float(rng.uniform(-0.12, 0.12) * height)
        max_x = max(0.0, 0.5 - width * 0.5)
        max_y = max(0.0, 0.5 - height * 0.5)
        offset_x = float(np.clip(offset_x + jitter_x, -max_x, max_x))
        offset_y = float(np.clip(offset_y + jitter_y, -max_y, max_y))
        views.append(
            {
                "offset_xy": [offset_x, offset_y],
                "size_xy": [width, height],
                "angle_degrees": float(rng.uniform(-22.0, 22.0)),
                "shape": shape,
                "depth": float(depth),
            }
        )
    return {
        "color": [float(v) / 255.0 if float(v) > 1.0 else float(v) for v in (*color, 255)[:4]],
        "depth": float(depth),
        "views": views,
        "placement": "model_projected_anchor",
    }


def _apply_mask_visualization(
    image_path: Path,
    mask: Image.Image,
    fill_color: tuple[int, int, int],
    alpha: float,
    outline_color: tuple[int, int, int],
    outline_width: int,
) -> None:
    image = Image.open(image_path).convert("RGB")
    alpha = float(np.clip(alpha, 0.0, 1.0))
    mask_l = mask.convert("L")
    if alpha >= 1.0:
        overlay = Image.new("RGB", image.size, fill_color)
        image.paste(overlay, mask=mask_l)
    elif alpha > 0.0:
        image_arr = np.asarray(image, dtype=np.float32)
        mask_arr = (np.asarray(mask_l, dtype=np.float32) / 255.0)[:, :, None]
        color_arr = np.asarray(fill_color, dtype=np.float32)
        blended = image_arr * (1.0 - mask_arr * alpha) + color_arr * (mask_arr * alpha)
        image = Image.fromarray(np.clip(blended, 0, 255).astype(np.uint8), mode="RGB")

    if outline_width > 0:
        edge = mask_l.filter(ImageFilter.FIND_EDGES)
        kernel_size = max(3, outline_width * 2 + 1)
        if kernel_size % 2 == 0:
            kernel_size += 1
        edge = edge.filter(ImageFilter.MaxFilter(kernel_size))
        outline = Image.new("RGB", image.size, outline_color)
        image.paste(outline, mask=edge)
    image.save(image_path)


def _load_npz_arrays(path: Path) -> dict[str, np.ndarray]:
    with np.load(path, allow_pickle=False) as npz:
        return {key: npz[key] for key in npz.files}


def _save_occluded_points(
    source_npz_path: Path,
    out_npz_path: Path,
    spec: OcclusionSpec,
    args: ProcessArgs,
    rng: np.random.Generator,
) -> dict[str, Any]:
    arrays = _load_npz_arrays(source_npz_path)
    if "points" not in arrays:
        raise ValueError(f"source npz has no points field: {source_npz_path}")
    source_points = np.asarray(arrays["points"], dtype=np.float32)
    if source_points.ndim != 2 or source_points.shape[1] != 3:
        raise ValueError(f"points must have shape Nx3: {source_npz_path}")

    removed_mask = _points_in_unit_box(source_points, spec.center_unit, spec.size_unit)
    keep_indices = np.flatnonzero(~removed_mask)
    removed_indices = np.flatnonzero(removed_mask)
    removed_ratio = float(removed_mask.mean()) if len(removed_mask) else 0.0
    if len(keep_indices) == 0:
        raise ValueError("point occlusion removed all source points")

    target_count = int(args.num_points or len(source_points))
    if args.fixed_num_points:
        replace = len(keep_indices) < target_count
        selected_indices = rng.choice(keep_indices, size=target_count, replace=replace)
    else:
        selected_indices = keep_indices

    out_points = source_points[selected_indices].astype(np.float32)
    save_kw: dict[str, np.ndarray] = {
        key: value for key, value in arrays.items() if key not in {"points", "point_mapping"}
    }
    save_kw["points"] = out_points
    save_kw["num_points"] = np.array([len(out_points)], dtype=np.int32)
    save_kw["source_indices"] = selected_indices.astype(np.int64)
    save_kw["removed_mask"] = removed_mask.astype(np.bool_)
    save_kw["removed_indices"] = removed_indices.astype(np.int64)
    save_kw["removed_ratio"] = np.array([removed_ratio], dtype=np.float32)
    save_kw["occlusion_center_unit"] = np.asarray(spec.center_unit, dtype=np.float32)
    save_kw["occlusion_size_unit"] = np.asarray(spec.size_unit, dtype=np.float32)
    save_kw["occlusion_mode"] = np.array([spec.mode])
    save_kw["source_point_path"] = np.array([str(source_npz_path)])
    if "point_mapping" in arrays and len(arrays["point_mapping"]) == len(source_points):
        save_kw["point_mapping"] = arrays["point_mapping"][selected_indices]

    out_npz_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(out_npz_path, **save_kw)
    return {
        "point_path": str(Path("points") / out_npz_path.name),
        "source_point_count": int(len(source_points)),
        "output_point_count": int(len(out_points)),
        "removed_point_count": int(removed_mask.sum()),
        "removed_ratio": removed_ratio,
        "resampled_with_replacement": bool(len(keep_indices) < target_count)
        if args.fixed_num_points
        else False,
    }


def _copy_points_for_foreground_occlusion(
    source_npz_path: Path,
    out_npz_path: Path,
) -> dict[str, Any]:
    arrays = _load_npz_arrays(source_npz_path)
    if "points" not in arrays:
        raise ValueError(f"source npz has no points field: {source_npz_path}")
    out_npz_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source_npz_path, out_npz_path)
    source_points = np.asarray(arrays["points"], dtype=np.float32)
    return {
        "point_path": str(Path("points") / out_npz_path.name),
        "source_point_count": int(len(source_points)),
        "output_point_count": int(len(source_points)),
        "removed_point_count": 0,
        "removed_ratio": 0.0,
        "resampled_with_replacement": False,
        "occlusion_visibility": "image_only",
    }


def _load_meshes_for_record(
    step_path: Path,
    args: ProcessArgs,
) -> tuple[trimesh.Trimesh, np.ndarray, float, str]:
    mesh_raw, _, loader = load_step_as_mesh(
        step_path,
        triangle_face_tol=args.triangle_face_tol,
        angle_tol_rads=args.angle_tol_rads,
    )
    mesh_centered = mesh_raw.copy()
    mesh_centered, _, _, scale, raw_center = normalize_trimesh_unit_cube(mesh_centered)
    return mesh_centered, raw_center, float(scale), loader


def _sample_spec(
    record: dict[str, Any],
    variant_index: int,
    args: ProcessArgs,
    points_for_sampling: np.ndarray,
    rng: np.random.Generator,
    seed: int,
) -> tuple[OcclusionSpec, dict[str, Any]]:
    sample_id = str(record.get("sample_id") or Path(record["step_path"]).stem)
    variant_id = f"occ_{variant_index:03d}"
    variant_sample_id = f"{sample_id}__{variant_id}"
    mode = args.mode
    if mode == "mixed":
        mode = str(rng.choice(["cutout", "occluder"]))

    if args.render_backend == "blender-step" and mode == "occluder":
        # Foreground occluders are sampled in screen space per view, not by
        # deleting a 3D region from the model.
        spec = OcclusionSpec(
            source_sample_id=sample_id,
            variant_id=variant_id,
            variant_sample_id=variant_sample_id,
            mode=mode,
            target_dims=args.target_dims,
            primitive="foreground_plane",
            center_unit=(0.5, 0.5, 0.5),
            size_unit=(0.0, 0.0, 0.0),
            seed=seed,
            views=args.num_views,
        )
        return spec, {
            "spec_attempts": 1,
            "sampling_removed_ratio": 0.0,
            "occlusion_visibility": "image_only",
        }

    best: Optional[tuple[float, np.ndarray, np.ndarray]] = None
    target_ratio = (args.min_removed_ratio + args.max_removed_ratio) * 0.5
    unit_points = _unit_points(points_for_sampling)
    if len(unit_points) == 0:
        raise ValueError("cannot sample occlusion spec from empty points")

    for attempt in range(args.max_spec_attempts):
        anchor = unit_points[int(rng.integers(0, len(unit_points)))]
        base_size = float(rng.uniform(args.size_min, args.size_max))
        aspect = rng.uniform(0.75, 1.25, size=3)
        size = np.clip(base_size * aspect, 1e-4, 1.0)
        center = np.clip(anchor + rng.normal(0.0, base_size * 0.20, size=3), 0.0, 1.0)
        removed = _points_in_unit_box(points_for_sampling, center, size)
        ratio = float(removed.mean()) if len(removed) else 0.0
        distance = abs(ratio - target_ratio)
        if best is None or distance < best[0]:
            best = (distance, center, size)
        if args.min_removed_ratio <= ratio <= args.max_removed_ratio:
            spec = OcclusionSpec(
                source_sample_id=sample_id,
                variant_id=variant_id,
                variant_sample_id=variant_sample_id,
                mode=mode,
                target_dims=args.target_dims,
                primitive="box",
                center_unit=tuple(float(x) for x in center),
                size_unit=tuple(float(x) for x in size),
                seed=seed,
                views=args.num_views,
            )
            return spec, {
                "spec_attempts": attempt + 1,
                "sampling_removed_ratio": ratio,
            }

    if best is None:
        raise ValueError("failed to sample occlusion spec")
    _, center, size = best
    removed = _points_in_unit_box(points_for_sampling, center, size)
    ratio = float(removed.mean()) if len(removed) else 0.0
    raise ValueError(
        "failed to sample occlusion spec within ratio range "
        f"[{args.min_removed_ratio}, {args.max_removed_ratio}] "
        f"after {args.max_spec_attempts} attempts; best={ratio:.4f}"
    )


def _render_images_and_masks(
    mesh_centered: trimesh.Trimesh,
    spec: OcclusionSpec,
    args: ProcessArgs,
    step_render_path: Optional[Path],
    raw_center: Optional[np.ndarray],
    scale: Optional[float],
) -> dict[str, Any]:
    image_dir = args.output_dir / "images" / spec.variant_sample_id
    mask_dir = args.output_dir / "masks" / spec.variant_sample_id
    mask_dir.mkdir(parents=True, exist_ok=True)
    fronts = get_view_fronts(args.num_views)

    stats: dict[str, Any] = {}
    if spec.mode == "cutout":
        _, cut_stats = _cutout_mesh_by_box(mesh_centered, spec)
        stats.update(cut_stats)

    foreground_occluder = None
    if args.render_backend == "blender-step":
        if step_render_path is None or raw_center is None or scale is None:
            raise ValueError("blender-step image rendering requires a STEP path and normalization")
        legacy_occluder = None
        if _uses_foreground_occluder(args, spec):
            foreground_occluder = _make_model_anchored_foreground_occluder_config(
                mesh_centered,
                fronts,
                args.img_size,
                spec.seed,
                args.occluder_color,
                args.foreground_occluder_size_min,
                args.foreground_occluder_size_max,
                args.foreground_occluder_depth,
            )
            stats["foreground_occluder"] = foreground_occluder
            stats["occlusion_visibility"] = "image_only"
        else:
            legacy_occluder = {
                "center_unit": list(spec.center_unit),
                "size_unit": list(spec.size_unit),
                "color": list(args.highlight_color),
            }
        image_paths = render_step_views_with_blender(
            step_render_path,
            image_dir,
            fronts,
            img_size=args.img_size,
            camera_distance=args.camera_distance,
            raw_center=raw_center,
            scale=float(scale),
            blender_bin=args.blender_bin,
            blender_script=args.blender_script,
            occluder=legacy_occluder,
            foreground_occluder=foreground_occluder,
            engine=args.blender_engine,
            samples=args.blender_samples,
            render_style=args.blender_style,
        )
    else:
        image_paths = render_views_to_png(
            mesh_centered,
            image_dir,
            fronts,
            img_size=args.img_size,
            camera_distance=args.camera_distance,
            render_width=args.render_width,
            render_height=args.render_height,
            render_backend=args.render_backend,
        )

    mask_paths: list[str] = []
    mask_area_ratios: list[float] = []
    for i, front in enumerate(fronts):
        if foreground_occluder is not None:
            mask = _foreground_mask_for_view(foreground_occluder["views"][i], args.img_size)
        else:
            mask = _visible_box_mask_for_view(mesh_centered, spec, front, args.img_size)
        mask_name = f"view_{i:03d}_mask.png"
        mask_path = mask_dir / mask_name
        mask.save(mask_path)
        mask_paths.append(str(Path("masks") / spec.variant_sample_id / mask_name))
        mask_arr = np.asarray(mask, dtype=np.uint8) > 0
        mask_area_ratios.append(float(mask_arr.mean()))
        if args.render_backend == "blender-step":
            continue
        if spec.mode == "occluder":
            image_path = args.output_dir / image_paths[i]
            _apply_mask_visualization(
                image_path,
                mask,
                fill_color=args.occluder_color,
                alpha=1.0,
                outline_color=args.outline_color,
                outline_width=args.outline_width,
            )
        elif spec.mode == "cutout" and args.highlight_cutout:
            image_path = args.output_dir / image_paths[i]
            _apply_mask_visualization(
                image_path,
                mask,
                fill_color=args.highlight_color,
                alpha=1.0,
                outline_color=args.outline_color,
                outline_width=args.outline_width,
            )

    stats.update(
        {
            "image_paths": image_paths,
            "mask_paths": mask_paths,
            "mask_area_ratios": mask_area_ratios,
            "mean_mask_area_ratio": float(np.mean(mask_area_ratios))
            if mask_area_ratios
            else 0.0,
            "cutout_highlight": bool(spec.mode == "cutout" and args.highlight_cutout),
            "highlight_color": list(args.highlight_color),
            "highlight_alpha": 1.0 if spec.mode == "cutout" else float(args.highlight_alpha),
            "outline_color": list(args.outline_color),
            "outline_width": int(args.outline_width),
            "render_backend": args.render_backend,
        }
    )
    return stats


def _export_step_cutout(
    step_path: Path,
    out_step_path: Path,
    spec: OcclusionSpec,
    raw_center: np.ndarray,
    scale: float,
) -> dict[str, Any]:
    if cq is None:
        raise RuntimeError("cadquery is required for STEP boolean cutout")
    if spec.mode != "cutout":
        raise ValueError("STEP export only supports mode=cutout")
    if scale <= 0:
        raise ValueError(f"invalid normalization scale: {scale}")

    center_raw = raw_center + (np.asarray(spec.center_unit, dtype=np.float64) - 0.5) / scale
    size_raw = np.asarray(spec.size_unit, dtype=np.float64) / scale
    if np.any(size_raw <= 0):
        raise ValueError(f"invalid raw cutout size: {size_raw}")

    source = cq.importers.importStep(str(step_path))
    tool = cq.Workplane("XY").box(
        float(size_raw[0]),
        float(size_raw[1]),
        float(size_raw[2]),
        centered=True,
    )
    tool = tool.translate(tuple(float(x) for x in center_raw))
    result = source.cut(tool)
    out_step_path.parent.mkdir(parents=True, exist_ok=True)
    cq.exporters.export(result, str(out_step_path))
    return {
        "step_variant_path": str(Path("steps") / out_step_path.name),
        "step_boolean_status": "ok",
        "cutout_center_raw": _as_float_list(center_raw),
        "cutout_size_raw": _as_float_list(size_raw),
    }


def _source_point_path(record: dict[str, Any], args: ProcessArgs) -> Optional[Path]:
    point_path = record.get("point_path")
    if not point_path:
        return None
    path = args.source_assets_dir / str(point_path)
    return path if path.is_file() else None


def _points_for_spec(
    record: dict[str, Any],
    args: ProcessArgs,
    mesh_centered: Optional[trimesh.Trimesh],
    rng: np.random.Generator,
) -> np.ndarray:
    point_path = _source_point_path(record, args)
    if point_path is not None:
        arrays = _load_npz_arrays(point_path)
        if "points" in arrays:
            return np.asarray(arrays["points"], dtype=np.float32)

    if mesh_centered is None:
        raise ValueError("no source point cloud and no mesh for spec sampling")
    points, _ = trimesh.sample.sample_surface(mesh_centered, 4096)
    if len(points) > 4096:
        indices = rng.choice(len(points), size=4096, replace=False)
        points = points[indices]
    return np.asarray(points, dtype=np.float32)


def _existing_record(
    record: dict[str, Any],
    variant_index: int,
    args: ProcessArgs,
) -> Optional[tuple[dict[str, Any], list[dict[str, Any]], dict[str, Any]]]:
    sample_id = str(record.get("sample_id") or Path(record["step_path"]).stem)
    variant_sample_id = f"{sample_id}__occ_{variant_index:03d}"
    label_path = args.output_dir / "labels" / f"{variant_sample_id}.json"
    if not args.skip_existing or not label_path.is_file():
        return None
    with label_path.open("r", encoding="utf-8") as f:
        label = json.load(f)
    manifest = dict(label.get("manifest_record", {}))
    if not manifest:
        manifest = {
            "sample_id": variant_sample_id,
            "source_sample_id": sample_id,
            "label_path": str(Path("labels") / f"{variant_sample_id}.json"),
            "status": "ok",
            "skipped_existing": True,
        }
    manifest["skipped_existing"] = True
    audit = dict(label.get("coverage_stats", {}))
    audit["sample_id"] = variant_sample_id
    audit["skipped_existing"] = True
    return manifest, [], audit


def process_one_variant(
    item: tuple[dict[str, Any], int, ProcessArgs],
) -> tuple[Optional[dict[str, Any]], list[dict[str, Any]], Optional[dict[str, Any]]]:
    record, variant_index, args = item
    cached = _existing_record(record, variant_index, args)
    if cached is not None:
        return cached

    source_sample_id = str(record.get("sample_id") or Path(record["step_path"]).stem)
    rel_step = str(record["step_path"])
    step_path = args.step_root / rel_step
    seed = _stable_seed(args.seed, source_sample_id, variant_index)
    rng = np.random.default_rng(seed)
    failures: list[dict[str, Any]] = []

    def failure(stage: str, err: Exception | str) -> dict[str, Any]:
        return {
            "source_sample_id": source_sample_id,
            "variant_index": variant_index,
            "step_path": rel_step,
            "stage": stage,
            "error": str(err),
        }

    try:
        needs_mesh = "image" in args.target_dims or "step" in args.target_dims
        mesh_centered: Optional[trimesh.Trimesh] = None
        raw_center = np.zeros(3, dtype=np.float64)
        scale = 1.0
        loader = None
        if needs_mesh:
            mesh_centered, raw_center, scale, loader = _load_meshes_for_record(
                step_path,
                args,
            )

        points_for_sampling = _points_for_spec(record, args, mesh_centered, rng)
        spec, sampling_stats = _sample_spec(
            record,
            variant_index,
            args,
            points_for_sampling,
            rng,
            seed,
        )

        coverage_stats: dict[str, Any] = {
            **sampling_stats,
            "step_boolean_status": "not_requested",
        }
        manifest_record: dict[str, Any] = {
            "sample_id": spec.variant_sample_id,
            "source_sample_id": spec.source_sample_id,
            "variant_id": spec.variant_id,
            "variant_type": "occlusion",
            "occlusion_mode": spec.mode,
            "primitive": spec.primitive,
            "step_path": rel_step,
            "source_step_path": rel_step,
            "target_dims": list(args.target_dims),
            "views": args.num_views,
            "status": "ok",
        }
        if loader is not None:
            manifest_record["loader"] = loader

        step_render_path = step_path
        needs_step_cutout = ("step" in args.target_dims and spec.mode == "cutout") or (
            "image" in args.target_dims
            and args.render_backend == "blender-step"
            and spec.mode == "cutout"
        )
        if needs_step_cutout:
            if mesh_centered is None:
                mesh_centered, raw_center, scale, loader = _load_meshes_for_record(
                    step_path,
                    args,
                )
            out_step_path = args.output_dir / "steps" / f"{spec.variant_sample_id}.step"
            try:
                step_stats = _export_step_cutout(
                    step_path,
                    out_step_path,
                    spec,
                    raw_center,
                    scale,
                )
                coverage_stats.update(step_stats)
                step_render_path = out_step_path
                if "step" in args.target_dims:
                    manifest_record["step_variant_path"] = step_stats["step_variant_path"]
                else:
                    manifest_record["render_step_path"] = step_stats["step_variant_path"]
            except Exception as e:
                coverage_stats["step_boolean_status"] = "failed"
                coverage_stats["step_boolean_error"] = str(e)
                failures.append(failure("step_boolean", e))
                if set(args.target_dims) == {"step"} or (
                    "image" in args.target_dims and args.render_backend == "blender-step"
                ):
                    return None, failures, None
        elif "step" in args.target_dims and _uses_foreground_occluder(args, spec):
            manifest_record["step_variant_path"] = rel_step
            coverage_stats["step_variant_path"] = rel_step
            coverage_stats["step_boolean_status"] = "not_applicable"

        if "point_cloud" in args.target_dims:
            point_path = _source_point_path(record, args)
            if point_path is None:
                raise ValueError(f"missing source point cloud for {source_sample_id}")
            out_point_path = args.output_dir / "points" / f"{spec.variant_sample_id}.npz"
            if _uses_foreground_occluder(args, spec):
                point_stats = _copy_points_for_foreground_occlusion(
                    point_path,
                    out_point_path,
                )
            else:
                point_stats = _save_occluded_points(
                    point_path,
                    out_point_path,
                    spec,
                    args,
                    rng,
                )
            coverage_stats.update(point_stats)
            manifest_record["point_path"] = point_stats["point_path"]

        if "image" in args.target_dims:
            if mesh_centered is None:
                mesh_centered, raw_center, scale, loader = _load_meshes_for_record(
                    step_path,
                    args,
                )
            image_stats = _render_images_and_masks(
                mesh_centered,
                spec,
                args,
                step_render_path=step_render_path,
                raw_center=raw_center,
                scale=scale,
            )
            coverage_stats.update(image_stats)
            manifest_record["image_paths"] = image_stats["image_paths"]
            manifest_record["mask_paths"] = image_stats["mask_paths"]

        label_path = args.output_dir / "labels" / f"{spec.variant_sample_id}.json"
        manifest_record["label_path"] = str(Path("labels") / label_path.name)
        label = {
            "occlusion_spec": spec.to_dict(),
            "source_record": record,
            "manifest_record": manifest_record,
            "coverage_stats": coverage_stats,
        }
        _json_dump(label_path, label)

        audit_record = {
            "sample_id": spec.variant_sample_id,
            "source_sample_id": spec.source_sample_id,
            "mode": spec.mode,
            "target_dims": list(args.target_dims),
            **coverage_stats,
        }
        return manifest_record, failures, audit_record
    except Exception as e:
        return None, [failure("process_variant", e)], None


def _pool_initializer() -> None:
    signal.signal(signal.SIGINT, signal.SIG_IGN)


def _write_jsonl(path: Path, records: Iterable[dict[str, Any]], mode: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open(mode, encoding="utf-8") as f:
        for record in records:
            f.write(json.dumps(record, ensure_ascii=True) + "\n")


def _summary(records: list[dict[str, Any]], failures: list[dict[str, Any]]) -> dict[str, Any]:
    def mean_of(key: str) -> Optional[float]:
        values = [float(r[key]) for r in records if key in r and r[key] is not None]
        return float(np.mean(values)) if values else None

    return {
        "ok": len(records),
        "failed": len(failures),
        "mean_removed_ratio": mean_of("removed_ratio"),
        "mean_sampling_removed_ratio": mean_of("sampling_removed_ratio"),
        "mean_mask_area_ratio": mean_of("mean_mask_area_ratio"),
        "step_boolean_ok": sum(
            1 for r in records if r.get("step_boolean_status") == "ok"
        ),
        "step_boolean_failed": sum(
            1 for f in failures if f.get("stage") == "step_boolean"
        ),
    }


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Generate point/image/STEP occlusion variants from a STEP asset manifest."
    )
    p.add_argument("--manifest", type=str, required=True, help="Source manifest.jsonl")
    p.add_argument(
        "--source-assets-dir",
        type=str,
        default=None,
        help="Root for source point_path/image_paths; defaults to manifest parent",
    )
    p.add_argument("--step-root", type=str, required=True, help="Root for source step_path")
    p.add_argument("--output-dir", type=str, required=True, help="Output root")
    p.add_argument("--variants-per-sample", type=int, default=1)
    p.add_argument(
        "--target-dims",
        type=str,
        default="point_cloud,image",
        help="Comma-separated subset of point_cloud,image,step",
    )
    p.add_argument(
        "--mode",
        type=str,
        default="cutout",
        choices=sorted(VALID_MODES),
        help="cutout removes geometry/points; occluder overlays image masks; mixed samples both",
    )
    p.add_argument("--num-views", type=int, default=6, choices=[1, 2, 4, 6])
    p.add_argument("--img-size", type=int, default=256)
    p.add_argument("--camera-distance", type=float, default=-0.9)
    p.add_argument("--render-width", type=int, default=500)
    p.add_argument("--render-height", type=int, default=500)
    p.add_argument(
        "--render-backend",
        type=str,
        default="auto",
        choices=["auto", "open3d", "software", "blender-step"],
    )
    p.add_argument("--blender-bin", type=str, default="blender")
    p.add_argument(
        "--blender-style",
        type=str,
        default="default",
        choices=["default", "visualization"],
        help="Blender render preset; visualization uses the bundled high-quality style",
    )
    p.add_argument(
        "--visualization-root",
        type=str,
        default=None,
        help=(
            "Path to visualization-tar; when using --blender-style visualization and "
            "--blender-bin is unchanged, its bundled blender/blender is used if present"
        ),
    )
    p.add_argument(
        "--blender-script",
        type=str,
        default=None,
        help="Blender Python renderer; defaults to cad_data_gen/render_step_with_blender.py",
    )
    p.add_argument(
        "--blender-engine",
        type=str,
        default="BLENDER_EEVEE_NEXT",
        choices=["BLENDER_EEVEE_NEXT", "BLENDER_EEVEE", "CYCLES"],
    )
    p.add_argument("--blender-samples", type=int, default=64)
    p.add_argument("--foreground-occluder-size-min", type=float, default=0.20)
    p.add_argument("--foreground-occluder-size-max", type=float, default=0.36)
    p.add_argument("--foreground-occluder-depth", type=float, default=0.45)
    p.add_argument("--triangle-face-tol", type=float, default=0.01)
    p.add_argument("--angle-tol-rads", type=float, default=0.1)
    p.add_argument("--size-min", type=float, default=0.18)
    p.add_argument("--size-max", type=float, default=0.45)
    p.add_argument("--min-removed-ratio", type=float, default=0.10)
    p.add_argument("--max-removed-ratio", type=float, default=0.35)
    p.add_argument("--max-spec-attempts", type=int, default=40)
    p.add_argument(
        "--num-points",
        type=int,
        default=None,
        help="Output point count; defaults to source count",
    )
    p.add_argument(
        "--variable-num-points",
        action="store_true",
        help="Keep all visible points instead of resampling back to a fixed count",
    )
    p.add_argument("--occluder-color", type=str, default="28,38,48")
    p.add_argument(
        "--no-cutout-highlight",
        action="store_true",
        help="Disable the projected highlight overlay for cutout renders",
    )
    p.add_argument(
        "--highlight-color",
        type=str,
        default="220,30,30",
        help="Projected cutout highlight fill color as R,G,B",
    )
    p.add_argument(
        "--highlight-alpha",
        type=float,
        default=0.45,
        help="Alpha for projected cutout highlight overlay",
    )
    p.add_argument(
        "--outline-color",
        type=str,
        default="110,0,0",
        help="Mask outline color as R,G,B",
    )
    p.add_argument(
        "--outline-width",
        type=int,
        default=1,
        help="Mask outline width in pixels after projection",
    )
    p.add_argument("--num-processes", type=int, default=1)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--limit", type=int, default=None)
    p.add_argument("--skip-existing", action="store_true")
    p.add_argument(
        "--append-manifest",
        action="store_true",
        help="Append manifest/failures/audit instead of overwriting",
    )
    return p.parse_args()


def main() -> None:
    ns = parse_args()
    manifest_path = Path(ns.manifest).resolve()
    source_assets_dir = (
        Path(ns.source_assets_dir).resolve()
        if ns.source_assets_dir is not None
        else manifest_path.parent.resolve()
    )
    step_root = Path(ns.step_root).resolve()
    output_dir = Path(ns.output_dir).resolve()
    if not manifest_path.is_file():
        print(f"manifest is not a file: {manifest_path}", file=sys.stderr)
        sys.exit(1)
    if not step_root.is_dir():
        print(f"step-root is not a directory: {step_root}", file=sys.stderr)
        sys.exit(1)
    if ns.variants_per_sample < 1:
        print("--variants-per-sample must be >= 1", file=sys.stderr)
        sys.exit(1)
    if not (0.0 <= ns.min_removed_ratio <= ns.max_removed_ratio <= 1.0):
        print("removed ratio range must satisfy 0 <= min <= max <= 1", file=sys.stderr)
        sys.exit(1)
    if not (0.0 < ns.size_min <= ns.size_max <= 1.0):
        print("size range must satisfy 0 < min <= max <= 1", file=sys.stderr)
        sys.exit(1)
    if not (0.0 <= ns.highlight_alpha <= 1.0):
        print("--highlight-alpha must be in [0, 1]", file=sys.stderr)
        sys.exit(1)
    if ns.outline_width < 0:
        print("--outline-width must be >= 0", file=sys.stderr)
        sys.exit(1)
    if not (0.0 < ns.foreground_occluder_size_min <= ns.foreground_occluder_size_max < 1.0):
        print("foreground occluder size range must satisfy 0 < min <= max < 1", file=sys.stderr)
        sys.exit(1)
    if not (0.0 < ns.foreground_occluder_depth < 1.0):
        print("--foreground-occluder-depth must be in (0, 1)", file=sys.stderr)
        sys.exit(1)
    try:
        blender_bin = resolve_blender_bin(
            ns.blender_bin,
            ns.blender_style,
            ns.visualization_root,
        )
    except RuntimeError as exc:
        print(str(exc), file=sys.stderr)
        sys.exit(1)

    args = ProcessArgs(
        source_assets_dir=source_assets_dir,
        step_root=step_root,
        output_dir=output_dir,
        target_dims=_parse_dims(ns.target_dims),
        mode=ns.mode,
        num_views=ns.num_views,
        img_size=ns.img_size,
        camera_distance=ns.camera_distance,
        render_width=ns.render_width,
        render_height=ns.render_height,
        render_backend=ns.render_backend,
        blender_bin=blender_bin,
        blender_script=Path(ns.blender_script).resolve()
        if ns.blender_script is not None
        else None,
        blender_engine=ns.blender_engine,
        blender_samples=ns.blender_samples,
        blender_style=ns.blender_style,
        foreground_occluder_size_min=ns.foreground_occluder_size_min,
        foreground_occluder_size_max=ns.foreground_occluder_size_max,
        foreground_occluder_depth=ns.foreground_occluder_depth,
        triangle_face_tol=ns.triangle_face_tol,
        angle_tol_rads=ns.angle_tol_rads,
        variants_per_sample=ns.variants_per_sample,
        seed=ns.seed,
        size_min=ns.size_min,
        size_max=ns.size_max,
        min_removed_ratio=ns.min_removed_ratio,
        max_removed_ratio=ns.max_removed_ratio,
        max_spec_attempts=ns.max_spec_attempts,
        num_points=ns.num_points,
        fixed_num_points=not ns.variable_num_points,
        occluder_color=_parse_color(ns.occluder_color),
        highlight_cutout=not ns.no_cutout_highlight,
        highlight_color=_parse_color(ns.highlight_color),
        highlight_alpha=ns.highlight_alpha,
        outline_color=_parse_color(ns.outline_color),
        outline_width=ns.outline_width,
        skip_existing=ns.skip_existing,
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    source_records = _load_manifest(manifest_path, ns.limit)
    jobs = [
        (record, variant_index, args)
        for record in source_records
        for variant_index in range(args.variants_per_sample)
    ]

    if ns.num_processes <= 1:
        results = [
            process_one_variant(job)
            for job in tqdm(jobs, desc="occlusion assets")
        ]
    else:
        pool = Pool(processes=ns.num_processes, initializer=_pool_initializer)
        try:
            results = list(
                tqdm(
                    pool.imap_unordered(
                        process_one_variant,
                        zip(
                            [job[0] for job in jobs],
                            [job[1] for job in jobs],
                            repeat(args),
                        ),
                    ),
                    total=len(jobs),
                    desc="occlusion assets",
                )
            )
        except KeyboardInterrupt:
            pool.terminate()
            pool.join()
            raise
        finally:
            pool.close()
            pool.join()

    manifest_records: list[dict[str, Any]] = []
    failure_records: list[dict[str, Any]] = []
    audit_records: list[dict[str, Any]] = []
    for source_index, (manifest_record, failures, audit_record) in enumerate(results):
        for failure in failures:
            failure["result_index"] = source_index
            failure_records.append(failure)
        if manifest_record is not None:
            manifest_record["result_index"] = source_index
            manifest_records.append(manifest_record)
        if audit_record is not None:
            audit_record["result_index"] = source_index
            audit_records.append(audit_record)

    write_mode = "a" if ns.append_manifest else "w"
    _write_jsonl(output_dir / "manifest.jsonl", manifest_records, write_mode)
    _write_jsonl(output_dir / "failures.jsonl", failure_records, write_mode)
    _write_jsonl(output_dir / "audit.jsonl", audit_records, write_mode)
    summary = _summary(audit_records, failure_records)
    summary.update(
        {
            "source_manifest": str(manifest_path),
            "source_assets_dir": str(source_assets_dir),
            "step_root": str(step_root),
            "output_dir": str(output_dir),
            "requested_jobs": len(jobs),
            "target_dims": list(args.target_dims),
            "mode": args.mode,
            "variants_per_sample": args.variants_per_sample,
            "seed": args.seed,
        }
    )
    _json_dump(output_dir / "summary.json", summary)
    print(
        "Done. "
        f"ok={len(manifest_records)} failed={len(failure_records)} "
        f"manifest={output_dir / 'manifest.jsonl'} "
        f"failures={output_dir / 'failures.jsonl'} "
        f"summary={output_dir / 'summary.json'}"
    )


if __name__ == "__main__":
    main()
